version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/TicketsBot/GoPanel

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install czlib
          command: sudo apt-get install -y zlib1g-dev

      - run: go build cmd/panel/main.go

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/GoPanel/main